# Generated by Django 4.1.1 on 2022-09-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
