# Generated by Django 4.1.1 on 2022-09-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0002_meetings_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_url', models.CharField(max_length=1000, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='participant_id',
        ),
        migrations.AddField(
            model_name='meetings',
            name='participant_email',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='participant_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meetings',
            name='participant_notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='join_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='start_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
