# Generated by Django 4.1.1 on 2022-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOGIN', '0003_participants_remove_meetings_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
