# Generated by Django 4.1.1 on 2022-09-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meetings',
        ),
    ]
